### PR TITLE
fix(language-core): correctly infer union props to options

### PR DESCRIPTION
**Pull request by KazariEX**
fix vuejs/core#12012 , fix vuejs/core#12110

### CODE REVIEW

**Comment by darkbasic** [comment]
Thanks, I've tested your patch and it fixed my issue.

**Review by davidmatter — APPROVED** [review]

**Comment by hendrikheil** [comment]
@KazariEX I think this would be a great addition. Currently there are typescript errors when you do the following:

```
<script setup lang="ts">
import { useCssModule } from 'vue';

const styles = useCssModule();

defineProps<
  | {
      option: 'a';
      aValue: string;
    }
  | {
      option: 'b';
      bValue: number;
    }
>();
</script>

<template>
  <div :class="styles.example">Option: {{ option }}</div>
</template>

<style lang="css" module>
.example {
  color: red;
}
</style>
```

As soon as you add the style module tag, vue and typescript are unable to properly see props and things like imported components. I tested your code locally and it seemed to have made the typescript errors in the template tag go away immediately. Do you think it makes sense to reconsider this PR?

**Comment by KazariEX** [comment]
According to Johnson's suggestion, a better approach is to place union types into generics to skip redundant type inferring and directly use the original types, which avoids injecting too much difficult to maintain code.

**Comment by darkbasic** [comment]
There are many issues with that approach. I started writing a comment about that but then I stumbled upon an even bigger bug regarding union props and unfortunately I still have to file it.

**Comment by hendrikheil** [comment]
I did try the generics approach as well, but that does cause other issues for me as well. I'll try to create a minimal component reproduction of the errors I'm encountering with it and post it here.

**Pull request closed without merging**
