### PR TITLE
test: add tests for #3488, #3518

### LINKED ISSUE #3488: Variable defined in `defineExpose` should not be available in `<template>`
If a variable is defined in `defineExpose`, then Volar thinks that it is also available for the template to grab:
```vue
<script setup lang="ts">
defineExpose({ x: 3 });
</script>

<template>
  x = "{{ x }}"
</template>
```
[playground](https://play.vuejs.org/#eNp9kT9PwzAQxb+KdRNIVRiyhRYJUAYYAAGjlyi5BhfHtvynWIr83Tk7amCouvne+53vnW6Ge2OqY0BoYOt6K4xnDn0wTHZq3HHwjsMdVwPuhcI2Gu3wamaxYTVL17dcbW+WLmKo8DgZ2XmkirHIdozDTDRLiUNmVx829HOv1V6M1cFpRePn3MOh15MREu2r8UIrmt6w4mSvk1L/PBfN24Cbk95/Yf99Rj+4mDUObxYd2iNyWD3f2RH9YrcfLxjpvZqTHoIk+oL5jk7LkDMu2ENQA8X+x5W0T5PR1gs1fro2elTutFQOmslUeA50g8cLq//Frau69HGVIP0CBnaS8A==)

If you hover over `{{ x }}` in the template, popup will say that it is a variable of type number, but runtime says that it is not defined at all.

### LINKED ISSUE #3518: Cannot override properties defined in `defineExpose` and `defineProps`
[Link](https://play.vuejs.org/#eNp9kc1OwzAQhF/F8qUgValKb1UaCVAPcIAKOPoSpdvg4tiWvSmVorw7u07/QMAhSjzzrTXZ6eSt99muBTmXeayC9igiYOsLZXXjXUBx7xovNsE1YpRN+MD4SNl8MvBE0gGh8aZEoJMQ+TDj3ELJ6c1MySJPk2TmkxMpxxJj5exG19k2OksROp5WsiJWGwjPHrWzUcm5SA57pTHu8zFpGFoYH/XqHaqPX/Rt3LOm5CpAhLADJU8elqEGHOzl6xPs6ftkNm7dGqL/MV8gOtNyxgG7a+2aYl9wKe1DWqS29Vtc7hFsPP4UB2WyT7yStFhe01+/fo47y2ZpTtmetngs5WeHwpS2pgqQrilUUHYNG21hFZyPeccC30s1zUXEQPlY6oura37zQ+VEZEAsxJSFc+cH4qL3w3Vdlwb6fuC/+bL/AlyU0Tk=)

Related: #3488

### PR DESCRIPTION
**Pull request by so1ve**
close #3488, close #3518

### CODE REVIEW

**Comment by so1ve** [comment]
@rchl Thanks! Updated.

**Comment by so1ve** [comment]
🤔 I should use `ts-expect-error`

**Comment by so1ve** [comment]
Note: #3488 and #3518 are not identical, but since they are highly related so I'll fix them in this PR at the same time

**Comment by johnsoncodehk** [comment]
Hi @so1ve, since #3488 has been fixed by #3591, we just keep the tests, thanks!

**Pull request merged**
