### PR TITLE
chore: add reply new issue workflow 

### PR DESCRIPTION
**Pull request by jahnli**
image

### CODE REVIEW

**Comment by rchl** [comment]
This seems pointless. The same could be conveyed in the initial issue template (which @johnsoncodehk said before that he doesn't want to have).

**Comment by so1ve** [comment]
We don't have an issue template. And this message is not helpful.

**Comment by jahnli** [comment]
github templates can be used

**Comment by jahnli** [comment]
In response to a question, actually
Questions are answered automatically, first-time contributors are welcome, and questions are regularly closed at......

**Pull request closed without merging**
