### PR TITLE
feat(language-core): type support of `useSlots` and `$slots`

### PR DESCRIPTION
**Pull request by KazariEX**

### CODE REVIEW

**Comment by darkbasic** [comment]
image

It used to infer `string | number` before the 2.2.0 update while now I get this error.

**Comment by darkbasic** [comment]
image

@KazariEX it used to infer `string | number` before the 2.2.0 update while now I get this error.

**Comment by darkbasic** [comment]
@KazariEX thanks, I'll use `Record<string, unknown>` otherwise I get this error:

image

**Comment by FaustineG** [comment]
Thank @KazariEX ! 

In my case, I didn't need to specify a type, simply `defineSlots();` removed the error. 

@darkbasic You could probably also use the `Slots` type from vue, it worked on another typing error for me.
image

**Comment by KazariEX** [comment]
You can also use:

```vue
<template v-for="render in $slots">
  <component :is="render" />
</template>
```

instead of `<slot>`.

**Pull request merged**
