### PR TITLE
feat: support nested plugins

### LINKED ISSUE #3437: Support nested plugins
In Rollup and Vite, we can put nested plugins in `plugins` property, like `{ plugins: [a, [b, c]]}`

I hope that we can also support this feature in `vueCompilerOptions.plugins`. So that we can avoid requiring users to configure all of the plugins.
https://vue-macros.sxzz.moe/guide/bundler-integration.html#volar-support

### PR DESCRIPTION
**Pull request by so1ve**
close #3437, supersedes #3528

### CODE REVIEW

**Comment by so1ve** [comment]
Currently I simply flatten all nested plugins. @sxzz How should we handle nested plugins with circular references? How does vite handle that case?

**Comment by sxzz** [comment]
Could you please make an example for me?

**Comment by so1ve** [comment]
Ugh. For example:

```ts
const plugin = []

plugin.push(plugin)
```

**Comment by sxzz** [comment]
@so1ve Vite and rollup won't handle this case. It's not a valid usage.

**Comment by johnsoncodehk** [comment]
Thanks!

**Pull request merged**
