### PR TITLE
feat: Support for `@vue-ignore`, `@vue-skip`, `@vue-expected-error` directive comments

### LINKED ISSUE #2366: Allow using `@ts-expect-error` in Vue templates
Hi all, and thanks again @johnsoncodehk for the amazing Volar.

I have a case on my Nuxt module (https://github.com/victorgarciaesgi/nuxt-typed-router), where I need to test types output of components.
I use `vue-tsc` to scan the fixtures to make sure things break where it should, and things are valid where it should.
It works well for ts files because I can use `@ts-expect-error`.
But on my case I want to test that the overrided types of `<NuxtLink/>` are working well.

The workaround I found for now is to use a .tsx and to test on a `render` function, but that miss the point the types are correctly injected into the global Vue scope.

What I can do in tsx:

```tsx
import {NuxtLink} from '@typed-router';

function render() {
  return (
        {/* @ts-expect-error */}
        <NuxtLink to={{ name: 'user-id', params: { foo: 'bar' } }}></NuxtLink>;
   )
}
```

What I want to do in vue templates:

image

### PR DESCRIPTION
**Pull request by johnsoncodehk**
Close #2366

Support 3 directive comment syntax for template.

`@vue-ignore`: Similar to `@ts-ignore`, ignore errors of the next template node. (Not just the next line)
`@vue-expected-error`: Similar to `@ts-expected-error`, report if the next template node has no errors.
`@vue-skip`: The next template node and its child nodes will skip generating virtual code.

## Usage

```html
<template>
  <!-- @vue-ignore -->
  <HelloWorld :msg="wrongType" />

  <!-- @vue-expected-error -->
  <HelloWorld :msg="wrongType" />

  <!-- @vue-skip -->
  <SomethingYouDontWantVolarToRecognizeIt>
    ...
  </SomethingYouDontWantVolarToRecognizeIt>
</template>
```

### CODE REVIEW

**Comment by Anoesj** [comment]
TypeScript uses `@ts-expect-error`, not `@ts-expected-error`. Other than that, great stuff! 😄

**Review by nekocom3745 — COMMENTED** [review]
packages/vue-language-core/src/generators/template.ts

**Review by nekocom3745 — COMMENTED** [review]
packages/vue-language-core/src/generators/template.ts

**Comment by johnsoncodehk** [comment]
@Anoesj Unfortunately bug 🤦, will fix it in the next release, thanks for the report.

**Comment by johnsoncodehk** [comment]
> TypeScript uses `@ts-expect-error`, not `@ts-expected-error`.

Fixed by https://github.com/vuejs/language-tools/commit/5696eb2a8aea8ccf2af9eed9e740d0c1a3361458

**Comment by saibotk** [comment]
What about allowing comments to follow the tags?

eg:
```vue
<!-- @vue-expect-error We could type this with some magic, but it would probably be complex to do -->

equivalent in ts:
// @ts-expect-error We could type this with some magic, but it would probably be complex to do
```

**Comment by wenfangdu** [comment]
> What about allowing comments to follow the tags?
> 
> eg:
> 
> ```
> 
> 
> equivalent in ts:
> // @ts-expect-error We could type this with some magic, but it would probably be complex to do
> ```

That's already supported.

**Comment by wenfangdu** [comment]
> What about allowing comments to follow the tags?
> 
> eg:
> 
> ```
> 
> 
> equivalent in ts:
> // @ts-expect-error We could type this with some magic, but it would probably be complex to do
> ```

@saibotk That's already supported in 1.8.0.

**Pull request merged**
