### PR TITLE
fix broken marketplace page

### PR DESCRIPTION
**Pull request by rioj7**
The current marketplace page is broken.

Cause adding literal html tags (script, template, style)

```none
Vue: Split <script>, <template>, <style> Editors
```

If put inside code ticks they are no longer interpreted as html tags.

```none
Vue: Split `<script>`, `<template>`, `<style>` Editors
```

Fix settings table by replacing the `|` character in an example by its HTML entity equivalent. (needs to use html code tags)

```none
Auto add space between double curly brackets: <code>{{&vert;}}</code> -> <code>{{ &vert; }}</code>
```

### CODE REVIEW

**Comment by lattaai6** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated README.md and package.json to fix issues with HTML tags in command descriptions and improve table formatting.

You can review changes in this commit: https://github.com/lattaai6/vuejs-language-tools-5004/commit/76671e1afa98f0cf95395029163e87b412f98bda.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Review by KazariEX — APPROVED** [review]

**Comment by KermanX** [comment]
Hmmm, this part of README is auto-generated by https://github.com/antfu/vscode-ext-gen. We can't just edit it. Instead, we should either:

- PR to https://github.com/antfu/vscode-ext-gen
- Remove this part, and disable generating this via a flag in the script

**Comment by rioj7** [comment]
@KermanX @KazariEX https://github.com/antfu/vscode-ext-gen v0.5.3 now has a Markdown Escape for text extracted from the `package.json` file

**Comment by KazariEX** [comment]
Could you please update the deps and readme?

**Comment by rioj7** [comment]
@KazariEX

Looking at the README Blame I see that `github-actions[bot]` has added a commit 2 days ago 74a1918a51 `ci(lint): auto-fix` that partially modified the effected lines. It has changed 1 `|` and 1 `<>` pair. But not all.

I made a small mistake in the `vscode-ext-gen` pull request. I have submitted a fix pull request.

It looks like the github actions fetch the latest `v0.5.x` `vscode-ext-gen` so no modification of `package.json` is needed.

According to KermanX that part of README is generated/replaced at each release build.

**Pull request merged**
