### PR TITLE
Feature: add feature about custom options to use own tsconfig.json

### PR DESCRIPTION
**Pull request by tsukuha**
## Abstract
I created pull request about this discussions https://github.com/vuejs/language-tools/discussions/4466

## About Test
- vue file
```index.vue
<script setup lang="ts">
	const a: number = ''
</script>

<template></template>
```
- tsconfig.json
```json
{
	"compilerOptions": {
		"strict": true,
	}
}
```
- command
```sh
./packages/tsc/bin/vue-tsc.js --project ./packages/tsc/playground/tsconfig.json ./packages/tsc/playground/index.vue
```
- logs
スクリーンショット 2024-06-14 13 50 01

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
First of all, thank you for your PR. `vue-tsc` itself already supports `tsc`'s `--project` option. Is this PR intended to achieve different behavior from the original `--project` option?

**Comment by tsukuha** [comment]
@johnsoncodehk 
Thanks for your reply.
I thought `vue-tsc` is not supported to set own tsconfig.json path by tsc's `--project` option.
I write reasons the reason below.

executed `vue-tsc@2.0.22`
```sh
$ npx vue-tsc --noEmit --project ./tsconfig.json ./pages/index.vue
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```
- index.vue
```
<script setup lang="ts">
function test(arr: string[]) {
  const a: string = arr[1]
}
</script>

<template>
  <div>
    <button type="button" @click="test([])"></button>
  </div>
</template>

```

- tsconfig.json
```json
{
	"compilerOptions": {
		"noEmit": true,
		"strict": true,
		"noUncheckedIndexedAccess": true,
	},
	"exclude": ["node_modules"]
}

```

according to your reply
> vue-tsc itself already supports tsc's --project option

It is a bug, isn't it?

I challenged to add code for fixed this problem, but I found this PR is still not enough fixed to this problem.

**Comment by tsukuha** [comment]
Oh, sorry.

I found it is a tsc's specification.
https://github.com/microsoft/TypeScript/issues/27379

I will close this PR and Discussion https://github.com/vuejs/language-tools/discussions/4466 .

**Comment by tsukuha** [comment]
this problem is a tsc's specification.

> Allow tsconfig.json when input files are specified #27379
https://github.com/microsoft/TypeScript/issues/27379

I will close this PR and Discussion https://github.com/vuejs/language-tools/discussions/4466 .

**Pull request closed without merging**
