### PR TITLE
refactor: better default inlay hint settings

### PR DESCRIPTION
**Pull request by wenfangdu**
- `"vue.inlayHints.missingProps": true` is very useful.
- `"vue.inlayHints.optionsWrapper": true` creates distraction, therefore changed to `false`.

Closes https://github.com/vuejs/language-tools/issues/2468#issuecomment-1537059127.

### CODE REVIEW

**Comment by rchl** [comment]
Why are you updating html data here? Those changes don't seem to be relevant to the issue. And also don't carry any meaningful changs.

**Comment by wenfangdu** [comment]
@rchl I'm wondering that too, it's triggered by CI, but using my name as the committer name:
image
image
It's rather confusing and scary, @johnsoncodehk can you please set the CI action to use the bot name as the committer name instead of the PR author name?

**Comment by wenfangdu** [comment]
@rchl I'm wondering that too, it's triggered by CI, but using my info as the committer info:
image
image
It's rather confusing and scary, @johnsoncodehk can you please set the CI action to use the bot info as the committer info instead of the PR author info?

**Comment by wenfangdu** [comment]
@rchl I'm wondering that too, it's triggered by CI, but using my info as the committer info:
image
image
It's rather confusing and scary, @johnsoncodehk can you please set the CI action to use the bot info as the committer info instead of the PR author info?

**Comment by wenfangdu** [comment]
@rchl And now it's committing on behalf of @johnsoncodehk 🤷‍♂️
image
image
Looks like it's using the last committer info to make the CI action commit.

**Comment by johnsoncodehk** [comment]
It used to be that `vue.inlayHints.optionsWrapper` was enabled by default because a lot of people didn't know why they had unexpected component types. I'll see if it can be enabled by default only for debug.

I decided not to enable `vue.inlayHints.missingProps` by default, since users can enable it themselves.

> It's rather confusing and scary, @johnsoncodehk can you please set the CI action to use the bot info as the committer info instead of the PR author info?

https://github.com/vuejs/language-tools/commit/e29e064c63dc637241029345660585ddb781e4bf should fixed the problem.

**Pull request merged**
