### PR TITLE
chore(readme): update discord link

### PR DESCRIPTION
**Pull request by codymikol**
Hello, I am currently using this project from within nvim via mason and was hoping to contribute.

I found that following the `README.md` to the discord link brought me to mostly NFT spam and unanswered community questions. I think it is probably best to remove this link until there is enough of a community around this project in particular to support moderation / questions from the community.

Also, if anyone can point me in a good direction to get information about a pipeline to build and load this within the nvim ecosystem I would really appreciate it.

Thanks for all your hard work!

```
there is no active moderation / community activity here. this is mostly filled with spam and unanswered questions.
```
Fixes N/A

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
This message is forwarded from "Volar Land" discord server.

```
Hi @everyone! I apologize that I've been very busy for a long time in the past and therefore unable to manage messages in the discord server, I'm looking for a more efficient way to solve this problem.

The mix of volar and vue-language-tools messages in this discord was the main reason for the difficulty.

After much deliberation, I've decided to shut down the discord server and move all vue discussions to the "Vue Land" discord server.

If you have unresolved issues with vue-language-tools, just resubmit it in the following "Vue Land" language-tools:

https://discord.com/channels/325477692906536972/1192748831633326160

If you are a tool developer who is integrating with Volar.js, we have opened a new discord server to replace the current one, which is intentionally smaller to ensure we can handle messages, please move to it and re-present your issue:

https://discord.gg/8ZaQDfBW

I will be actively answering questions over the next few days. This discord server will be deleted in 2 weeks. Sorry for the inconvenience, and thank you for your understanding.
```

Can you update the discord link to https://discord.com/channels/325477692906536972/1192748831633326160?

**Comment by codymikol** [comment]
Sure!

I did notice though, that the link you provided only works if you are already in the Vue Land server, if not it is borked

image

I'll see if I can find a way to do a channel invite

**Comment by codymikol** [comment]
Looks like I'm only allowed to invite to the server, let me know if the format I pushed is acceptable

**Comment by johnsoncodehk** [comment]
LGTM, thanks!

**Pull request merged**
