### PR TITLE
feat(language-core): typed fallthrough attributes

### LINKED ISSUE #4699: attribute inheritance when strictTemplates enabled
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.92.2

### Vue version

3.4.29

### TypeScript version

5.4.0

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 7840U w/ Radeon  780M Graphics
    Memory: 13.28 GB / 30.66 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 127.0.6533.119
```

### Steps to reproduce

Enable `strictTemplates: true` and run type-check on vue templates that contain certain fallthrough attributes/events like `id` on a component:

```vue
<HelloWorld msg="You did it!" id="4" />
```

The other attributes that don't work are `title` and `aria-*` attributes.

Another problem is with the `@click` event listener on components that use `defineModel` (see repro link)

### What is expected?

No typechecking errors are expected as attributes like `id` and `aria-label` should be treated as allowed fallthrough attributes.

### What is actually happening?

Type check fails with errors (`Object literal may only specify known properties`):

```
src/App.vue:15:37 - error TS2353: Object literal may only specify known properties, and 'id' does not exist in type 'Partial<{}> & Omit<{ readonly msg?: string | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...>, never>'.

15       <HelloWorld msg="You did it!" id="4" />
```

### Link to minimal reproduction

https://github.com/Doeke/bug-stricttemplates

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by so1ve**
close #4049. close #4699.

Should add `Co-authored-by: A5rocks <git@helvetica.moe>` as a co-author

---

~~This now requires adding an option `experimentalInheritAttrs` to `vueCompilerOptions`.~~

### CODE REVIEW

**Comment by so1ve** [comment]
I have no idea about #2472 💦

**Comment by johnsoncodehk** [comment]
Merged, well done! Next we can add highlighting to the target tag of fallthrough attributes.

**Comment by teleskop150750** [comment]
@johnsoncodehk 
Thank you for your amazing work.
Will there be support for object partitioning in the future?
I tried changing the code in the test and it failed

`test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs/inherit-attrs-false-v-bind.vue`

```vue
<script>
import { defineComponent } from 'vue';

export default defineComponent({
	inheritAttrs: false,
});
</script>

<script setup lang="ts">
import child from './child.vue';
</script>

<template>
	<child v-bind="{...$attrs}"></child>
</template>
```

```
Error: Snapshot `vue-tsc > TypeScript - Stable 1` mismatched

- Expected
+ Received

  [
    "test-workspace/tsc/failureFixtures/directives/main.vue(4,6): error TS2339: Property 'notExist' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { exist: typeof exist; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.",
    "test-workspace/tsc/failureFixtures/directives/main.vue(9,6): error TS2339: Property 'notExist' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { exist: typeof exist; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.",
    "test-workspace/tsc/failureFixtures/directives/main.vue(12,2): error TS2578: Unused '@ts-expect-error' directive.",
+   "test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs/main.vue(15,26): error TS2353: Object literal may only specify known properties, and 'bar' does not exist in type 'Partial<{}> & Omit<{} & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<ExtractPropTypes<{}>>, never>'.",
  ]

 ❯ packages/tsc/tests/typecheck.spec.ts:10:5
 ```

**Comment by teleskop150750** [comment]
@johnsoncodehk 
Thank you for the amazing work.
Will there be future support for object destructuring.
I tried to change the test code and it failed

`test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs/inherit-attrs-false-v-bind.vue`

```vue
<script>
import { defineComponent } from 'vue';

export default defineComponent({
	inheritAttrs: false,
});
</script>

<script setup lang="ts">
import child from './child.vue';
</script>

<template>
	<child v-bind="{...$attrs}"></child>
</template>
```

```
Error: Snapshot `vue-tsc > TypeScript - Stable 1` mismatched

- Expected
+ Received

  [
    "test-workspace/tsc/failureFixtures/directives/main.vue(4,6): error TS2339: Property 'notExist' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { exist: typeof exist; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.",
    "test-workspace/tsc/failureFixtures/directives/main.vue(9,6): error TS2339: Property 'notExist' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { exist: typeof exist; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.",
    "test-workspace/tsc/failureFixtures/directives/main.vue(12,2): error TS2578: Unused '@ts-expect-error' directive.",
+   "test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs/main.vue(15,26): error TS2353: Object literal may only specify known properties, and 'bar' does not exist in type 'Partial<{}> & Omit<{} & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<ExtractPropTypes<{}>>, never>'.",
  ]

 ❯ packages/tsc/tests/typecheck.spec.ts:10:5
 ```

**Comment by teleskop150750** [comment]
@johnsoncodehk 
Thank you for the amazing work.
Will there be future support for object destructuring.
I tried to change the test code and it failed

`test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs/inherit-attrs-false-v-bind.vue`

```vue
<script>
import { defineComponent } from 'vue';

export default defineComponent({
  inheritAttrs: false,
});
</script>

<script setup lang="ts">
import child from './child.vue';
</script>

<template>
  <child v-bind="{...$attrs}"></child>
</template>
```

```
Error: Snapshot `vue-tsc > TypeScript - Stable 1` mismatched

- Expected
+ Received

  [
    "test-workspace/tsc/failureFixtures/directives/main.vue(4,6): error TS2339: Property 'notExist' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { exist: typeof exist; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.",
    "test-workspace/tsc/failureFixtures/directives/main.vue(9,6): error TS2339: Property 'notExist' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { exist: typeof exist; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.",
    "test-workspace/tsc/failureFixtures/directives/main.vue(12,2): error TS2578: Unused '@ts-expect-error' directive.",
+   "test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs/main.vue(15,26): error TS2353: Object literal may only specify known properties, and 'bar' does not exist in type 'Partial<{}> & Omit<{} & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<ExtractPropTypes<{}>>, never>'.",
  ]

 ❯ packages/tsc/tests/typecheck.spec.ts:10:5
 ```
 
 
 For example, in Radix UI, user events are often wrapped
 
```vue
<script setup lang="ts">
import { useAttrs } from 'vue'
import { Primitive } from '../primitive/index.ts'
import { isFunction } from '../utils/is.ts'
import { composeEventHandlers } from '../utils/vue.ts'
import { useDialogContext } from './Dialog.ts'
import type { DialogTriggerProps } from './DialogTrigger.ts'
import { getState } from './utils.ts'

defineOptions({
  name: 'DialogTrigger',
  inheritAttrs: false,
})

withDefaults(defineProps<DialogTriggerProps>(), {
  as: 'button',
})
const attrs = useAttrs()

const context = useDialogContext('DialogTrigger')

const onClick = composeEventHandlers((event) => {
  if (isFunction(attrs.onClick))
    attrs.onClick(event)
}, context.onOpenToggle)
</script>

<template>
  <Primitive
    :ref="(nodeRef: any) => {
      const node = nodeRef ? nodeRef.$el : undefined
      context.triggerRef.current = node
    }"
    :as="as"
    :as-child="asChild"
    type="button"
    aria-haspopup="dialog"
    :aria-expanded="context.open.value || false"
    :aria-controls="context.open.value ? context.contentId : undefined"
    :data-state="getState(context.open.value)"
    v-bind="{
      ...attrs,
      onClick,
    }"
  >
    <slot />
  </Primitive>
</template>
```

**Comment by johnsoncodehk** [comment]
Since this feature would significantly impact type checking speed, this feature was changed in https://github.com/vuejs/language-tools/commit/ebb84900b890ddd6b793a8fe78c19d87dc2d7f38 to require `fallthroughAttributes` to be explicitly enabled in tsconfig.

**Comment by johnsoncodehk** [comment]
This is a minimal recurrence of the case of slow tsc when `fallthroughAttributes` is enabled.

```ts
import { defineComponent } from 'vue';

const Foo = defineComponent({
	props: {} as __VLS_TypePropsToOption<{ bar?: string }>,
});
const Bar = defineComponent({
	props: {} as __VLS_TypePropsToOption<FooAttrs>,
});
defineComponent({
	setup() {
		return {};
	},
	props: {} as __VLS_TypePropsToOption<BarAttrs>,
});

type FooAttrs = __VLS_OmitIndexSignature<Partial<InstanceType<typeof Foo>['$props']>>;
type BarAttrs = __VLS_OmitIndexSignature<Partial<InstanceType<typeof Bar>['$props']>>;

type __VLS_TypePropsToOption<T> = {
	[K in keyof T]-?: {} extends Pick<T, K>
	? { type: import('vue').PropType<T[K]> }
	: { type: import('vue').PropType<T[K]>, required: true }
};
type __VLS_OmitIndexSignature<T> = { [K in keyof T as {} extends Record<K, unknown> ? never : K]: T[K]; };
```

**Pull request merged**
