### PR TITLE
fix: generate valid code when using __VLS_PropsChildren

### PR DESCRIPTION
**Pull request by so1ve**

### CODE REVIEW

**Comment by rchl** [comment]
Is this not testable?

**Comment by so1ve** [comment]
@rchl We can't test it (and we don't have to) because it doesn't break the functionality without this fix.

**Comment by rchl** [comment]
Why we can't test it? Is it because the type is `any` without this change and still doesn't fail?

**Comment by so1ve** [comment]
@rchl Though it creates invalid code without this fix, it is functioning correctly - correct types and completions.

**Pull request merged**
